apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: set-fsgroup
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces: ["system"]
  location: "spec.containers[name:*].securityContext.fsGroup"
  parameters:
    assign:
      value: 174988

