apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
