apiVersion: v1
kind: Pod
metadata:
  namespace: mohsin
  name: test
spec:
  containers:
    - image: busybox
      command: ['sh', '-c', 'sleep 600']
      name: test
      ports:
        - containerPort: 80
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
