#!/usr/bin/with-contenv bash
cd "${HOME}"
mkdir -p ${HOME}/conda_cache
exec /opt/conda/bin/jupyter lab \
  --notebook-dir="${HOME}" \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --port=8888 \
  --ServerApp.token="" \
  --ServerApp.password="" \
  --ServerApp.allow_origin="*" \
  --ServerApp.base_url="${NB_PREFIX}" \
  --ServerApp.authenticate_prometheus=False \
  --ServerApp.max_body_size=5368709120 \
  --ServerApp.max_buffer_size=5368709120
