# Use the respective Makefile to pass the appropriate BASE_IMG and build the image correctly
ARG BASE_IMG=<base>
FROM $BASE_IMG

USER root

# args - software versions
ARG MINIFORGE_ARCH="x86_64"
 # renovate: datasource=github-tags depName=conda-forge/miniforge versioning=loose
ARG MINIFORGE_VERSION=4.10.1-4
ARG PIP_VERSION=21.1.2
#ARG PYTHON_VERSION=3.8.10
ARG PYTHON_VERSION=3.9.10
ARG OF_VERSION=2012

# Jupyter Lab installation

# install -- node.js
RUN export DEBIAN_FRONTEND=noninteractive \
 && curl -sL "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" | apt-key add - \
 && echo "deb https://deb.nodesource.com/node_14.x focal main" > /etc/apt/sources.list.d/nodesource.list \
 && apt-get -yq update \
 && add-apt-repository ppa:rock-core/qt4 \
 && apt-get -yq install --no-install-recommends \
    nodejs build-essential patch cmake zlib1g-dev \
    gnuplot libreadline-dev libncurses-dev libxt-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


# setup environment for conda
ENV CONDA_DIR /opt/conda
ENV PATH "${CONDA_DIR}/bin:${PATH}"
RUN mkdir -p ${CONDA_DIR} \
 && echo ". /opt/conda/etc/profile.d/conda.sh" >> ${HOME}/.bashrc \
 && echo ". /opt/conda/etc/profile.d/conda.sh" >> /etc/profile \
 && echo "conda activate base" >> ${HOME}/.bashrc \
 && echo "conda activate base" >> /etc/profile \
 && chown -R ${NB_USER}:${NB_GROUP} ${CONDA_DIR} \
 && chown -R ${NB_USER}:${NB_GROUP} ${HOME}


# switch to NB_UID for installs
USER ${NB_UID}

# install - conda, pip, python
RUN curl -sL "https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-${MINIFORGE_ARCH}.sh" -o /tmp/Miniforge3.sh \
 && curl -sL "https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-${MINIFORGE_ARCH}.sh.sha256" -o /tmp/Miniforge3.sh.sha256 \
 && echo "$(cat /tmp/Miniforge3.sh.sha256 | awk '{ print $1; }') /tmp/Miniforge3.sh" | sha256sum --check \
 && rm /tmp/Miniforge3.sh.sha256 \
 && /bin/bash /tmp/Miniforge3.sh -b -f -p ${CONDA_DIR} \
 && rm /tmp/Miniforge3.sh \
 && conda config --system --set auto_update_conda false \
 && conda config --system --set show_channel_urls true \
 && echo "conda ${MINIFORGE_VERSION:0:-2}" >> ${CONDA_DIR}/conda-meta/pinned \
 && echo "python ${PYTHON_VERSION}" >> ${CONDA_DIR}/conda-meta/pinned \
 && conda install -y -q \
    python=${PYTHON_VERSION} \
    conda=${MINIFORGE_VERSION:0:-2} \
    pip=${PIP_VERSION} \
 && conda update -y -q --all \
 && conda clean -a -f -y \
 && chown -R ${NB_USER}:${NB_GROUP} ${CONDA_DIR} \
 && chown -R ${NB_USER}:${NB_GROUP} ${HOME}

# install - requirements.txt
COPY --chown=${NB_USER}:${NB_GID} requirements.txt /tmp
RUN conda install -y -c conda-forge mamba \ 
 && mamba install -y -c conda-forge jupyterlab notebook ipykernel nb_conda_kernels nodejs\
 && python3 -m pip install -r /tmp/requirements.txt --quiet --no-cache-dir \
 && rm -f /tmp/requirements.txt \
 && jupyter lab --generate-config \
 && rm -rf ${HOME}/.cache/yarn \
 && chown -R ${NB_USER}:${NB_GROUP} ${CONDA_DIR} \
 && chown -R ${NB_USER}:${NB_GROUP} ${HOME}

# s6 - copy scripts
COPY --chown=${NB_USER}:${NB_GROUP} s6/ /etc

# s6 - 01-copy-tmp-home
USER root
RUN mkdir -p /tmp_home \
 && cp -r ${HOME} /tmp_home \
 && chown -R ${NB_USER}:${NB_GROUP} /tmp_home

# OpenFOAM-Installation

USER root
WORKDIR /software
RUN git clone -c feature.manyFiles=true https://github.com/spack/spack.git

#Set environment variables
ENV SPACK_ROOT=/software/spack
ENV SPACK_PYTHON=/opt/conda/bin/python3
ENV PATH="$PATH:/software/spack/bin/"


# create spack env
RUN source /software/spack/share/spack/setup-env.sh
RUN spack env create myenv 
RUN sed -i "7s:\[\]:\[gcc@9.4.0,openfoam@2206\]:" ./spack/var/spack/environments/myenv/spack.yaml 
RUN spack -e myenv install -vvv -y



