#!/usr/bin/with-contenv bash
cd "${HOME}"
source /apps/CFD/OpenFOAM-v2012/etc/bashrc
export FOAM_USER_APPBIN=/sw/${WM_PROJECT}-${WM_PROJECT_VERSION}/platforms/linux64GccDPInt32Opt/bin
export FOAM_USER_LIBBIN=/sw/${WM_PROJECT}-${WM_PROJECT_VERSION}/platforms/linux64GccDPInt32Opt/lib
export PATH=${FOAM_APPBIN}:${FOAM_USER_APPBIN}:${PATH}
export LD_LIBRARY_PATH=${FOAM_LIBBIN}:${FOAM_USER_LIBBIN}:${LD_LIBRARY_PATH}


exec /opt/conda/bin/jupyter lab \
  --notebook-dir="${HOME}" \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --port=8888 \
  --ServerApp.token="" \
  --ServerApp.password="" \
  --ServerApp.allow_origin="*" \
  --ServerApp.base_url="${NB_PREFIX}" \
  --ServerApp.authenticate_prometheus=False
