apiVersion: v1
kind: PersistentVolume
metadata:
  name: soccernet-pv
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/local/scratch/shaima0d-datasets" 