apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "dist"
  namespace: default
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              imagePullPolicy: IfNotPresent
              command: [ "nvidia-smi","-L"]
              resources:
                limits:
                  cpu: 2
                  memory: '2Gi'
                  nvidia.com/gpu: 1

              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm

          volumes:
            - emptyDir:
                medium: Memory
              name: dshm
