apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: my-environments
  namespace: training01
spec:
 selector:
  matchLabels:
    my-environments: "true"
 desc: "User environments"
 volumeMounts:
 - name: sw-volume
   mountPath: /sw
   readOnly: false
 volumes:
 - name: sw-volume
   hostPath:
           path: /mnt/sw
           type: Directory
