# Request a MIG using nodeSelector
apiVersion: v1
kind: Pod
metadata:
  name: cuda
spec:
  restartPolicy: Never
  containers:
    - name: cuda
      image: docker.io/mshaikh/kubeflow-demo:cuda-samples-11.6.0
      imagePullPolicy: Always
      command: [ "deviceQuery"]
      resources:
        requests:
          nvidia.com/gpu: 8
        limits:
          nvidia.com/gpu: 8
  nodeSelector:
        nvidia.com/gpu.product: 'NVIDIA-A100-SXM4-80GB-MIG-1g.10gb'

