apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "dist"
  namespace: default
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              imagePullPolicy: Always
              command: [ "torchrun", 
                          "/workspace/mnist/src/ddp.py",
                          "--num-workers","4",
                          "--batch-size","32"]
              env:
                - name: 'NCCL_DEBUG'
                  value: 'INFO'
                - name: 'DATA_DIR'
                  value: '/data/tiny-imagenet-200'
                - name: 'NCCL_IB_DISABLE'
                  value: '1'
                  
              resources: 
                limits:
                  cpu: 4
                  memory: '16Gi'
                  nvidia.com/gpu: 1

    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              imagePullPolicy: Always
              command: [ "torchrun", 
                          "/workspace/mnist/src/ddp.py",
                          "--num-workers","4",
                          "--batch-size","32"]
              env:
                - name: 'NCCL_DEBUG'
                  value: 'INFO'
                - name: 'DATA_DIR'
                  value: '/data/tiny-imagenet-200'
                - name: 'NCCL_IB_DISABLE'
                  value: '1'
              resources: 
                limits:
                  cpu: 4
                  memory: '16Gi'
                  nvidia.com/gpu: 1

                          
