apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "dist"
  namespace: training01
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              args: ["--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              args: ["--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
