apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "dist"
  namespace: default
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: docker.io/mshaikh/kubeflow-demo:kf-dist-torch-vanilla
              imagePullPolicy: Always
              command: [ "torchrun",
                         "--nnodes", "1",
                         "--nproc_per_node","4",
                         "/workspace/mnist/src/ddp.py",
                         "--batch-size","32",
                         "--num-worker","8",]
              env:
                - name: 'NCCL_DEBUG'
                  value: 'INFO'
                - name: 'DATA_DIR'
                  value: '/data/tiny-imagenet-200'
                - name: 'NCCL_DEBUG_SUBSYS'
                  value: 'ALL'
                - name: 'OMP_NUM_THREADS'
                  value: '1'
              resources: 
                limits:
                  cpu: 8
                  memory: '50Gi'
                  nvidia.com/gpu: 4